apiVersion: v1
data:
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  annotations:
    replicator.v1.mittwald.de/replicate-from: cloud-utils/dev-wildcard-tls
    replicator.v1.mittwald.de/replicated-keys: tls.crt,tls.key
  name: billing-gateway-tls
type: Opaque