---
apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-gateway-config
data:
  PORT: "8080"
  RUN_ENV: "production"
  CONV_SRV_URL: "http://converter.kubecon2023.svc.cluster.local:7001"
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: apikey-secret
# type: Opaque
# data:
#   apikey.txt: c3VwZXJzZWNyZXR2YWx1ZQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-gateway
  labels:
    app: billing-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-gateway
  template:
    metadata:
      labels:
        app: billing-gateway
    spec:
      containers:
      - name: app
        image: "frankgu968/kubecon2023-billing-gateway:latest"
        ports:
        - name: app
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: billing-gateway-config
      #   volumeMounts:
      #   - name: apikey-volume
      #     mountPath: /tmp/billing-gateway/mounts
      #     readOnly: true
      # volumes:
      # - name: apikey-volume
      #   secret:
      #     secretName: apikey-secret
      #     items:
      #     - key: apikey.txt
      #       path: apikey.txt
---
apiVersion: v1
kind: Service
metadata:
  name: billing-gateway
spec:
  selector:
    app: billing-gateway
  ports:
    - name: app
      protocol: TCP
      port: 7000
      targetPort: 8080