FROM node:18-alpine as builder

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json tsconfig.json ./
RUN npm ci

COPY src/ src/
RUN npm run build

FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm ci --only=production
COPY --from=builder /usr/src/app/build ./build

CMD [ "npm", "run", "start" ]